-- HIVE: complete database setup. Paste ALL of this into the Supabase SQL editor and press Run.
-- Safe to run again (every statement is idempotent). Generated by scripts/build-setup-sql.sh from
-- supabase/migrations/*.sql; edit those, not this file.

-- ================================================================ 0001_hive.sql

-- HIVE schema for Supabase (Postgres 15+).
--
-- Public (anon / authenticated may SELECT, nothing else): hives, actions, harvests, prices.
-- Private (service_role only; RLS on with no policies AND privileges revoked): launches, cell_claims,
-- secrets, meta, locks.
-- The server uses the service-role key, which bypasses RLS. Browsers use the anon key for reads and
-- Realtime (hives / actions / harvests are in the supabase_realtime publication).
--
-- Re-running this file is safe: tables / indexes use IF NOT EXISTS, functions CREATE OR REPLACE,
-- policies are dropped and recreated, grants are re-applied. It does NOT alter columns of tables that
-- already exist: schema changes go in a new numbered migration.
--
-- Timestamps are timestamptz; the app converts to/from epoch ms (lib/shared/rows.ts).

-- ---------------------------------------------------------------- public tables

create table if not exists public.hives (
  ca            text primary key,
  name          text not null,
  ticker        text not null,
  image         text not null default '',
  description   text,
  motto         text,
  telegram      text,
  twitter       text,
  cell_q        integer not null,
  cell_r        integer not null,
  queen_wallet  text not null,
  owner_wallet  text not null,
  look          jsonb,
  rules         jsonb,
  temperament   jsonb,
  dev_buy       numeric not null default 0 check (dev_buy >= 0),
  status        text not null check (status in ('mock', 'live')),
  create_tx     text,
  honey         numeric not null default 0,
  bees          integer not null default 0 check (bees >= 0),
  fees_total    numeric not null default 0,
  royal_jelly   numeric not null default 0,
  price         double precision,
  state         text not null default 'working' check (state in ('working', 'starving', 'abandoned')),
  last_fee_at   timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint hives_cell_unique unique (cell_q, cell_r),
  constraint hives_queen_wallet_unique unique (queen_wallet)
);

create table if not exists public.actions (
  id          text primary key,
  ca          text not null,
  verb        text not null check (verb in ('seal', 'store', 'swarm', 'starve', 'abandon', 'jelly', 'born')),
  amount      numeric not null default 0,
  target_ca   text,
  reason      text not null default '',
  tx_sig      text,
  at          timestamptz not null,
  dry_run     boolean not null default false
);
create index if not exists actions_ca_at_idx on public.actions (ca, at desc);
create index if not exists actions_at_idx on public.actions (at desc);

create table if not exists public.harvests (
  id            text primary key,
  at            timestamptz not null,
  fees_in       numeric not null default 0,
  hive_bought   numeric not null default 0,
  burned        numeric not null default 0,
  jelly_to      text not null default '',
  jelly_amount  numeric not null default 0,
  jelly_sol     numeric not null default 0,
  tx_sig        text not null default '',
  dry_run       boolean not null default false
);
create index if not exists harvests_at_idx on public.harvests (at desc);

create table if not exists public.prices (
  ca      text not null,
  at      timestamptz not null,
  price   double precision not null check (price >= 0),
  -- (ca, at) unique: re-recording the same snapshot replaces it; also serves the (ca, at) range scans
  constraint prices_pkey primary key (ca, at)
);

-- ---------------------------------------------------------------- private tables

create table if not exists public.launches (
  id               text primary key,
  mode             text not null check (mode in ('mock', 'live')),
  state            text not null check (state in ('reserved', 'paid', 'metadata', 'created', 'live', 'failed', 'expired', 'refunded')),
  owner            text not null,
  payload          jsonb not null,
  queen_wallet     text not null,
  mint_pubkey      text not null unique,
  mint_secret_enc  text not null,
  cell_q           integer not null,
  cell_r           integer not null,
  lamports         bigint not null check (lamports >= 0),
  created_at       timestamptz not null default now(),
  expires_at       timestamptz not null,
  updated_at       timestamptz not null default now(),
  ca               text,
  metadata_uri     text,
  image_uri        text,
  txs              jsonb not null default '{}'::jsonb,
  error            text,
  attempts         integer not null default 0
);
create index if not exists launches_state_idx on public.launches (state, created_at);

-- One row per reserved cell. expires_at null = permanent (the hive is live).
create table if not exists public.cell_claims (
  q           integer not null,
  r           integer not null,
  launch_id   text not null,
  expires_at  timestamptz,
  created_at  timestamptz not null default now(),
  constraint cell_claims_pkey primary key (q, r)
);
create index if not exists cell_claims_launch_idx on public.cell_claims (launch_id);

create table if not exists public.secrets (
  pubkey      text primary key,
  enc         text not null,
  created_at  timestamptz not null default now()
);

create table if not exists public.meta (
  key         text primary key,
  value       text not null,
  updated_at  timestamptz not null default now()
);

create table if not exists public.locks (
  name    text primary key,
  until   timestamptz not null
);

-- ---------------------------------------------------------------- row level security

alter table public.hives       enable row level security;
alter table public.actions     enable row level security;
alter table public.harvests    enable row level security;
alter table public.prices      enable row level security;
alter table public.launches    enable row level security;
alter table public.cell_claims enable row level security;
alter table public.secrets     enable row level security;
alter table public.meta        enable row level security;
alter table public.locks       enable row level security;

drop policy if exists hives_public_read on public.hives;
create policy hives_public_read on public.hives for select to anon, authenticated using (true);
drop policy if exists actions_public_read on public.actions;
create policy actions_public_read on public.actions for select to anon, authenticated using (true);
drop policy if exists harvests_public_read on public.harvests;
create policy harvests_public_read on public.harvests for select to anon, authenticated using (true);
drop policy if exists prices_public_read on public.prices;
create policy prices_public_read on public.prices for select to anon, authenticated using (true);
-- (no policies on launches, cell_claims, secrets, meta, locks: invisible to anon / authenticated)

-- Defence in depth: Supabase grants ALL on new public tables to anon / authenticated by default and
-- relies on RLS alone. Take the write privileges (and TRUNCATE, which RLS does not cover) away too.
revoke all on public.hives, public.actions, public.harvests, public.prices from anon, authenticated;
grant select on public.hives, public.actions, public.harvests, public.prices to anon, authenticated;
revoke all on public.launches, public.cell_claims, public.secrets, public.meta, public.locks from anon, authenticated;
grant all on
  public.hives, public.actions, public.harvests, public.prices,
  public.launches, public.cell_claims, public.secrets, public.meta, public.locks
  to service_role;

-- ---------------------------------------------------------------- atomic helpers

-- Take the lock `name` until `until` if it is free or expired. True when taken.
-- One INSERT .. ON CONFLICT statement, so concurrent callers serialise on the row.
create or replace function public.try_lock(name text, until timestamptz)
returns boolean
language sql
security definer
set search_path = public, pg_temp
as $$
  with taken as (
    insert into public.locks as l (name, until)
    values (try_lock.name, try_lock.until)
    on conflict on constraint locks_pkey do update
      set until = excluded.until
      where l.until <= now()
    returning 1
  )
  select exists (select 1 from taken);
$$;

-- Reserve cell (q, r) for `launch` until `expires` (null = permanent). True when reserved.
--  * false if a hive already stands there or another launch holds an unexpired / permanent claim;
--  * an expired unfinalized claim on the cell is deleted first, so the cell is free again;
--  * idempotent for the same launch (a retry refreshes a pending claim's expiry);
--  * a launch holds at most one pending cell: its other unfinalized claims are dropped.
create or replace function public.claim_cell(q integer, r integer, launch text, expires timestamptz)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
#variable_conflict use_variable
declare
  holder text;
begin
  if q is null or r is null or launch is null or launch = '' then
    return false;
  end if;
  if exists (select 1 from public.hives h where h.cell_q = q and h.cell_r = r) then
    return false;
  end if;

  delete from public.cell_claims c
   where c.q = q and c.r = r and c.expires_at is not null and c.expires_at <= now();

  select c.launch_id into holder from public.cell_claims c where c.q = q and c.r = r for update;
  if found then
    if holder <> launch then
      return false;
    end if;
    update public.cell_claims c set expires_at = expires
     where c.q = q and c.r = r and c.expires_at is not null;
    return true;
  end if;

  begin
    insert into public.cell_claims as c (q, r, launch_id, expires_at) values (q, r, launch, expires);
  exception when unique_violation then
    return false; -- someone else claimed it between our check and insert
  end;

  delete from public.cell_claims c
   where c.launch_id = launch and c.expires_at is not null and not (c.q = q and c.r = r);
  return true;
end;
$$;

-- Postgres grants EXECUTE to PUBLIC by default and Supabase also grants it to anon / authenticated:
-- only the service role may call these.
revoke execute on function public.try_lock(text, timestamptz) from public, anon, authenticated;
revoke execute on function public.claim_cell(integer, integer, text, timestamptz) from public, anon, authenticated;
grant execute on function public.try_lock(text, timestamptz) to service_role;
grant execute on function public.claim_cell(integer, integer, text, timestamptz) to service_role;

-- ---------------------------------------------------------------- realtime

-- Browsers receive INSERT / UPDATE on these tables (filtered by the SELECT policies above).
do $$
declare
  t text;
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    raise notice 'publication supabase_realtime not found: skipping realtime setup';
    return;
  end if;
  if (select puballtables from pg_publication where pubname = 'supabase_realtime') then
    return; -- FOR ALL TABLES already covers them
  end if;
  foreach t in array array['hives', 'actions', 'harvests'] loop
    if not exists (
      select 1 from pg_publication_tables
       where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end
$$;

-- ================================================================ 0002_live.sql

-- HIVE migration 0002: live-mode helpers. Run after 0001_hive.sql (Postgres 15+ / Supabase).
--
--  1. Preview (mock) hives never block a real launch. A live database can still hold preview rows
--     (test launches before go-live, or a mock deployment sharing the database): the old
--     hives_cell_unique (cell_q, cell_r) constraint becomes one unique index per status, so a live hive
--     may stand on a cell a preview hive occupies (the public reads of a live server never show
--     preview hives). Two hives of the same status still never share a cell.
--  2. claim_live_cell(q, r, launch, expires): claim_cell for live launches. Preview hives do not count
--     and a claim held by a mock-mode launch gives way. claim_cell itself is unchanged (mock mode).
--  3. hive_schema_info(): a report for /api/health and `npm run check:live`: schema version, which
--     tables / functions exist, realtime publication membership, and how much preview / dry-run data
--     is left (supabase/cleanup-fake-data.sql removes it). Booleans and counts only, no row data.
--
-- Re-running this file is safe: every statement is IF [NOT] EXISTS / CREATE OR REPLACE, grants are
-- re-applied. 0001 stays valid on its own; the server falls back to claim_cell without this file.

-- 0001 must have run first: say so plainly instead of failing on a missing table.
do $guard$ begin
  if to_regclass('public.hives') is null then
    raise exception 'HIVE tables are missing. Run supabase/setup.sql (the whole file) first.';
  end if;
end $guard$;

-- ---------------------------------------------------------------- one cell per hive, per status

alter table public.hives drop constraint if exists hives_cell_unique;
create unique index if not exists hives_live_cell_unique on public.hives (cell_q, cell_r) where status = 'live';
create unique index if not exists hives_mock_cell_unique on public.hives (cell_q, cell_r) where status = 'mock';

-- ---------------------------------------------------------------- claim_live_cell

-- Same contract as claim_cell (0001), except that preview data does not occupy cells:
--  * false if a non-preview hive stands on the cell or another live launch holds an unexpired /
--    permanent claim; hives with status 'mock' are ignored;
--  * an expired claim, and any claim held by a mode 'mock' launch, is deleted first;
--  * idempotent for the same launch; a launch holds at most one pending cell.
create or replace function public.claim_live_cell(q integer, r integer, launch text, expires timestamptz)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
#variable_conflict use_variable
declare
  holder text;
begin
  if q is null or r is null or launch is null or launch = '' then
    return false;
  end if;
  if exists (select 1 from public.hives h where h.cell_q = q and h.cell_r = r and h.status <> 'mock') then
    return false;
  end if;

  delete from public.cell_claims c
   where c.q = q and c.r = r and c.expires_at is not null and c.expires_at <= now();
  delete from public.cell_claims c
   where c.q = q and c.r = r and c.launch_id <> launch
     and exists (select 1 from public.launches l where l.id = c.launch_id and l.mode = 'mock');

  select c.launch_id into holder from public.cell_claims c where c.q = q and c.r = r for update;
  if found then
    if holder <> launch then
      return false;
    end if;
    update public.cell_claims c set expires_at = expires
     where c.q = q and c.r = r and c.expires_at is not null;
    return true;
  end if;

  begin
    insert into public.cell_claims as c (q, r, launch_id, expires_at) values (q, r, launch, expires);
  exception when unique_violation then
    return false; -- someone else claimed it between our check and insert
  end;

  delete from public.cell_claims c
   where c.launch_id = launch and c.expires_at is not null and not (c.q = q and c.r = r);
  return true;
end;
$$;

-- ---------------------------------------------------------------- hive_schema_info

create or replace function public.hive_schema_info()
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with
    want_tables(t) as (values ('hives'), ('actions'), ('harvests'), ('prices'), ('launches'), ('cell_claims'), ('secrets'), ('meta'), ('locks')),
    want_functions(f) as (values ('try_lock'), ('claim_cell'), ('claim_live_cell'), ('hive_schema_info')),
    pub as (select puballtables from pg_publication where pubname = 'supabase_realtime')
  select jsonb_build_object(
    'version', 2,
    'tables', (select coalesce(jsonb_agg(t order by t), '[]'::jsonb) from want_tables where to_regclass('public.' || t) is not null),
    'functions', (select coalesce(jsonb_agg(f order by f), '[]'::jsonb) from want_functions
                   where exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = f)),
    'rls', (select coalesce(bool_and(c.relrowsecurity), false) from pg_class c join pg_namespace n on n.oid = c.relnamespace
             where n.nspname = 'public' and c.relkind = 'r' and c.relname in (select t from want_tables)),
    'realtime', jsonb_build_object(
      'publication', exists (select 1 from pub),
      'allTables', coalesce((select puballtables from pub), false),
      'tables', (select coalesce(jsonb_agg(tablename::text order by tablename), '[]'::jsonb) from pg_publication_tables
                  where pubname = 'supabase_realtime' and schemaname = 'public' and tablename in ('hives', 'actions', 'harvests'))),
    'preview', jsonb_build_object(
      'hives', (select count(*) from public.hives where status = 'mock'),
      'launches', (select count(*) from public.launches where mode = 'mock'),
      'dryRunActions', (select count(*) from public.actions where dry_run),
      'dryRunHarvests', (select count(*) from public.harvests where dry_run)),
    'live', jsonb_build_object(
      'hives', (select count(*) from public.hives where status = 'live'),
      'launches', (select count(*) from public.launches where mode = 'live'))
  );
$$;

-- Server-only, like the 0001 helpers (Postgres and Supabase grant EXECUTE to PUBLIC / anon by default).
revoke execute on function public.claim_live_cell(integer, integer, text, timestamptz) from public, anon, authenticated;
revoke execute on function public.hive_schema_info() from public, anon, authenticated;
grant execute on function public.claim_live_cell(integer, integer, text, timestamptz) to service_role;
grant execute on function public.hive_schema_info() to service_role;
