#!/usr/bin/env bash
# Regenerate supabase/setup.sql: every migration in order, as ONE file to paste into the Supabase SQL
# editor. scripts/test-sql.sh fails when setup.sql is out of date.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
{
  echo "-- HIVE: complete database setup. Paste ALL of this into the Supabase SQL editor and press Run."
  echo "-- Safe to run again (every statement is idempotent). Generated by scripts/build-setup-sql.sh from"
  echo "-- supabase/migrations/*.sql; edit those, not this file."
  for m in "$ROOT"/supabase/migrations/*.sql; do
    echo
    echo "-- ================================================================ $(basename "$m")"
    echo
    cat "$m"
  done
} > "${1:-$ROOT/supabase/setup.sql}"
